checks:
  argument-count:
    enabled: false
  return-statements:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
  nested-control-flow:
    enabled: false
engines:
  eslint:
    enabled: true
    config: .eslintrc.json
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
ratings:
  paths:
  - "**.js"